services:

  cats-dogs-api:
    image: ankita5296/cats-dogs-api:latest

    ports:
      - "8000:8000"

    networks:
      - mlops-network

    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v3.14.0

    ports:
      - "9090:9090"

    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    networks:
      - mlops-network

    depends_on:
      - cats-dogs-api

    restart: unless-stopped


  grafana:
    image: grafana/grafana:13.2.0

    ports:
      - "3000:3000"

    networks:
      - mlops-network

    depends_on:
      - prometheus

    volumes:
      - grafana-data:/var/lib/grafana

    restart: unless-stopped


networks:

  mlops-network:
    name: cats-dogs-mlops-network
    driver: bridge


volumes:

  grafana-data: